### ISSUE TITLE
Crash on world join In Dev if both TipsyLib and Iron's Spellbooks are loaded

### ISSUE THREAD

**Issue by muon-rw** [Yirmiri/TipsyLib#6]
You can view the full log here:
https://mclo.gs/YSdiNOC

The relevant bit seems to be this (repeated several times):
```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.isClientSide()" because "self.level" is null
--
7670 | at net.minecraft.world.entity.LivingEntity.handler$zjl000$isCurrentlyGlowing(LivingEntity.java:7783) ~[forge-1.20.1-47.1.62_mapped_parchment_2023.07.16-1.20.1-recomp.jar%23191!/:?]
7671 | at net.minecraft.world.entity.LivingEntity.isCurrentlyGlowing(LivingEntity.java) ~[forge-1.20.1-47.1.62_mapped_parchment_2023.07.16-1.20.1-recomp.jar%23191!/:?]
7672 | at net.minecraft.world.entity.Entity.setGlowingTag(Entity.java:2411) ~[forge-1.20.1-47.1.62_mapped_parchment_2023.07.16-1.20.1-recomp.jar%23191!/:?]
7673 | at net.minecraft.world.entity.Entity.load(Entity.java:1869) ~[forge-1.20.1-47.1.62_mapped_parchment_2023.07.16-1.20.1-recomp.jar%23191!/:?]
7674 | ... 18 more
```

This mixin from Iron's is where `isCurrentlyGlowing` is running this check: https://github.com/iron431/irons-spells-n-spellbooks/blob/50631c43be33d5d06bcfba115628fb6fbd4dbe84/src/main/java/io/redspace/ironsspellbooks/mixin/LivingEntityMixin.java#L49

Probably caused by/related to #5

**Comment by KekeCreations** [comment]
This issue is fixed in V2.0.9.

Just a friendly reminder the mod got rewritten in 1.21 and instead of having tons of effects we turned them into attributes so they can be used in different ways! You can still use something like kubejs to create effects with the attributes and I created a tutorial on how to do this on the wiki. All effects in 1.20.1 will be recreatable in 1.21 using kubejs!

Thank you for reporting issues!
